### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MinecraftSTL** [xianyongjian080402/Minecraft-Optimal-Starter_3#11]
### 开始之前……

- [x] 我已经认真阅读[说明文件(Githib)](https://github.com/xianyongjian080402/Minecraft-Optimal-Starter_2/blob/master/.github/ISSUE_TEMPLATE/ISSUE_GUIDELINES.md)/[说明文件(Gitee)](https://gitee.com/xian66/minecraft-optimal-starter_2/blob/master/.gitee/ISSUE_GUIDELINES.md)

### Bug描述

在第一次启动时，如果在欢迎页面停留过久 会闪退（日志系统报错

### 复现方法(重现步骤)

第一次启动MOS启动器，不要做任何操作

### 期望的效果

第一次启动MOS启动器，等待直到我做出操作

### 实际效果

程序闪退，日志系统报错

### 日志

![X DP_99~R}8O9~J 9 TP{%5](https://user-images.githubusercontent.com/53145859/198859870-37460f1d-428b-45ae-a4e4-503f0ec30243.png)

### 备注

你让我提的

**Comment by David-Xian66** [comment]
已在 [aa8a77c](https://github.com/xianyongjian080402/Minecraft-Optimal-Starter_3/commit/aa8a77c105f8666462ed03c709493e17b536cda5) 中修复
